### PR TITLE
Fundraising

### PR DESCRIPTION
**Pull request by AndySheu**
Initial commit. Will shorten text soon

### CODE REVIEW

**Comment by AndySheu** [comment]
I'm probably going to create a new page with the fundraising stuff to shorten the text block on the front page.

**Comment by Joshua-Anderson** [comment]
@ClubCharger Needs a rebase.

``` shell
$ git checkout master
$ git pull origin master
$ git checkout fundraising
$ git rebase master
# Fix all the errors
$ git add .
$ git rebase --continue
$ git push origin fundraising -f
```

**Comment by gautam-prab** [comment]
this clearly needs fixing. I'll do it once I get through the other PRs

**Comment by gautam-prab** [comment]
I rebased this but at this point I think the best course of action is just to add the IndieGoGo to Team Support.

Team Support and Fundraising are too similar anyways.

**Comment by gautam-prab** [comment]
I closed this, but feel free to open if y'all don't agree with me

**Pull request closed without merging**
