### PR TITLE
put the social media stuff in a thing

### PR DESCRIPTION
**Pull request by AndySheu**
yeah

### CODE REVIEW

**Comment by AndySheu** [comment]
It looks a bit ugly, though

**Comment by Joshua-Anderson** [comment]
@ClubCharger Yeah, it doesn't look any better. If you can make this look better that would be nice

**Comment by AndySheu** [comment]
I'm ok with just closing it.

**Comment by Joshua-Anderson** [comment]
Ok. Feel free to create a new PR if can make this look better later.

**Pull request closed without merging**
