### PR TITLE
table funs

### PR DESCRIPTION
**Pull request by AndySheu**
it looks soon much more amazing and doesn’t use an HTML tag.

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Nice start, I like the look, but it still needs some work (for chrome at least)
screenshot from 2015-11-23 17-25-10

**Comment by AndySheu** [comment]
k. I think I know how to fix it. I'll push a fix tomorrow. It should work universally

**Comment by Joshua-Anderson** [comment]
@ClubCharger That didn't fix it. You want to make the table a variable width so it doesn't have a scrollbar (except when it gets really small).

**Comment by Joshua-Anderson** [comment]
Still needs some work on mobile. Can you please get rid of the scrollbar?

screenshot from 2015-12-01 17-34-08

**Pull request closed without merging**
