### PR TITLE
Added facebook and a little more content to website

### PR DESCRIPTION
**Pull request by gautam-prab**
Added a bit more content to website and added Facebook like button.
Note that when pressed, the Facebook like button tries to create a "you liked this" bubble which is huge and gets hidden because it goes beyond what the box shows. Not really a problem though because it doesn't really get in the way and it will go away if we reload/click away from it

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Looks good at first glance, but I want to quickly test it.

**Comment by Joshua-Anderson** [comment]
I'm fine with going too square icons as well

**Comment by gautam-prab** [comment]
I added a commit... did that work?

**Comment by Joshua-Anderson** [comment]
I need to actually test this on a computer, so I'll check this out tomarrow after school

**Comment by Joshua-Anderson** [comment]
Optimized icons. LGTM!

**Pull request merged**
