### PR TITLE
Everything looks amazing now

### PR DESCRIPTION
**Pull request by AndySheu**
Yay!

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
@ClubCharger Mobile friendlyness :sob:

screenshot from 2015-11-12 17-11-45

**Comment by Joshua-Anderson** [comment]
Could you re-pr with just the buttons? I'm okay with them, but the header I'm not so sure of and it needs a lot more work

**Comment by gautam-prab** [comment]
I'm not sure what this is.

**Comment by Joshua-Anderson** [comment]
@gautam-prab @ClubCharger added icons to buttons and changed the header

**Comment by Joshua-Anderson** [comment]
I'm going to close this, since the buttons were merged. If you want to clean it up and try again feel free.

**Pull request closed without merging**
