### PR TITLE
Added join team page

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
@gautam-prab or @ClubCharger do you want to add more content and give this a fully page?

### CODE REVIEW

**Comment by gautam-prab** [comment]
I'd prefer to give it a full page and not ask people to read the student registration packet if they're just considering joining, seeing as much of it is paperwork.

I'll write up a full page.

**Comment by Joshua-Anderson** [comment]
@gautam-prab :+1: See slack for some more suggestions.

**Comment by gautam-prab** [comment]
Added a commit; also made Calendar wide so that it didn't look awkward.

**Comment by gautam-prab** [comment]
Josh, can you make it so that button areas default to being at the very bottom of a card? I had to add newlines to ensure calendar and student info line up

**Pull request closed without merging**
