### PR TITLE
Added Student info Page

### PR DESCRIPTION
**Pull request by AndySheu**
Also edited title, mentioned CVR, stuffs, links to things.
@gautam-prab @Joshua-Anderson Changes?

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
@gautam-prab I actually like the calendar card smaller. It looks a little awkward right now, but we will add other smaller cards in the future.

**Comment by Joshua-Anderson** [comment]
Also, I think our student registration packet is too well hidden. I'd also add a button linking to it on the card.

**Comment by Joshua-Anderson** [comment]
@iron-claw-972/website-editors Done Reviewing!

**Comment by Joshua-Anderson** [comment]
Ok. Fixed up everything that I saw. Do we want a button on the card linking to the student packet?

**Comment by AndySheu** [comment]
Sure

**Comment by gautam-prab** [comment]
I hate that new button, by the way.
But I'll let it be for now.

**Pull request merged**
