### PR TITLE
Sponsors page

### PR DESCRIPTION
**Pull request by gautam-prab**
Note that this certainly needs work –
1. Smartphone support: I hope to be able to make it so that on a smartphone, it just shows logos instead of logos and company names. That would be ideal, but I'm not sure how this would be done.
2. Logos: logos are initial and some (hint, hint ANS) look kinda bad. Josh can do his imagey optimize thing and perhaps we should upload better pictures, and we should likely ask NMF if they want us to use a particular logo (I grabbed one from google because their normal logo is white).
3. Other: Rural Supply Hardware and ACE Hardware LG have same logo, so I put them in the same row. This may be unfair, but I'm not sure what else to do. Initially, I forgot to put links to websites, but I'll commit that within a few minutes.

### CODE REVIEW

**Comment by gautam-prab** [comment]
Added links. Note that the Brin-Wojcicki Foundation has no website (that I can find). I'm considering just removing the labels entirely; that'll solve the smartphone dilemma. Thoughts?

**Comment by gautam-prab** [comment]
Added a button. Used the business_center icon for some fresh new stuff. We can use the school icon for the mentors page.

**Comment by AndySheu** [comment]
A lot of the logos touch the table lines

**Comment by AndySheu** [comment]
Consider only having one column and having the images be links

**Comment by AndySheu** [comment]
A big problem with that is Rural Supply Hardware and ACE Hardware, though

**Comment by AndySheu** [comment]
Gold tier looks weird on desktop with 3/1 format.

**Comment by AndySheu** [comment]
Also, what about Rural Supply Hardware and Slack?

**Comment by AndySheu** [comment]
Possibly also specify what those tiers mean (such as dollar amount or something like that).

**Comment by AndySheu** [comment]
"Without our sponsors, we would be unable to buy our robot or our tools and we would not be able to sign up for competition." Replace "buy" with "build" I think. Buy our robot makes it seem like we didn't actually do it. Also, perhaps pluralify competition =D. So competitions?

**Comment by Joshua-Anderson** [comment]
> Gold tier looks weird on desktop with 3/1 format.

I personally think it looks fine. Alternatives would be to make the images larger so we got 2/2 on a normal screen.

screenshot from 2015-12-30 13-06-08

> Possibly also specify what those tiers mean (such as dollar amount or something like that).

Most places don't do that.

> "Without our sponsors, we would be unable to buy our robot or our tools and we would not be able to sign up for competition." Replace "buy" with "build" I think. Buy our robot makes it seem like we didn't actually do it. Also, perhaps pluralify competition =D. So competitions?.

I task @gautam-prab with this cause he wrote it.

**Comment by AndySheu** [comment]
Why is "gold tier" header 3 while silver and bronze are header 4?

**Comment by gautam-prab** [comment]
Did some stuff! Changed Josh's weird ordering, added two ACE's for Rural Supply Hardware and LG ACE Hardware, changed the link for ANS back to what I _originally_ had (the RRSD), and added slack

**Comment by gautam-prab** [comment]
> Why is "gold tier" header 3 while silver and bronze are header 4?

Cuz gold tier gave us more $$$

**Comment by Joshua-Anderson** [comment]
@gautam: H1 is largest H6 is smallest. Also, slack has not sponsored us, so I wouldn't add them.

**Comment by AndySheu** [comment]
Didn't they give us a premium plan, though?

**Comment by AndySheu** [comment]
So they should be the same level as GitHub, right?

**Comment by Joshua-Anderson** [comment]
We should also add a thank parents and etc about their sponsorships.

**Comment by Joshua-Anderson** [comment]
Nah. We're just using their free trial right now.

**Comment by Joshua-Anderson** [comment]
LGTM

**Pull request merged**
